### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by fenollp** [instantpage/instant.page#1]
Could you publish a browser extension? Or maybe there's already one and I missed it?
In particular it shouldn't clash with extensions such as https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab?hl=en
Thanks

**Comment by david-a-wheeler** [comment]
The problem is that only websites will know whether or not pre-loading a page is okay. So having a website tell you is no problem, but an extension would have no clue about any particular link.

**Comment by fenollp** [comment]
Well, I would. And I could maintain a blacklist of links/regexps too.

**Comment by ibrokemycomputer** [comment]
> Well, I would. And I could maintain a blacklist of links/regexps too.

I highly doubt you would know whether any link on any site is 'ok' to preload... Sorry if this seems blunt and/or uneducated, but that seems like a per-site deal (regardless of certain visible HTML attributes in the DOM)

**Comment by fenollp** [comment]
Look I'm not saying this browser extension would be for everyone. Indeed some links are not meant to be preloaded (sign out, deletion, ...) but there is no insidious act here: I'm willingly activating this extension.
I can maintain a global/per-subTLD black/white list of URL patterns like a big boy. There could also be a process to review/accept items on these lists to be merged into the extension.

**Comment by dieulot** [comment]
I’m considering doing a Chrome/Firefox extension.

I’ll have to think more about it, but currently I think it should be activated on any site by default, with a button to deactivate it on a specific site, like uBlock Origin does.

It would only preload links without a query string, but there would be exceptions, for instance Hacker News’s link to comments.

It would also probably be a good idea to enable it for external links.

**Comment by dieulot** [comment]
It’s done for Chrome: https://chrome.google.com/webstore/detail/fasterchrome/nmgpnfccjfjhdenioncabecepjcmdnjg

For Firefox, I’ll wait until pages don’t have to be put in cache to be prefetched (#7).

**Comment by grahamperrin** [comment]
> … For Firefox, …

Via <https://redd.it/e5v4wq>: 

* [Faster Pageload](https://addons.mozilla.org/addon/faster-pageload/) by @simonfrey
