### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by migueldemoura** [instantpage/instant.page#10]
Great work! Would it be possible to publish this as an npm package?

**Edit**: there seems to be an [npm package](https://www.npmjs.com/package/instant.page), can you confirm you are its owner?

**Comment by dieulot** [comment]
I am. (The [package.json](https://github.com/instantpage/instant.page/blob/master/package.json) tells so.)

**Comment by dimitarnestorov** [comment]
Anyone could've pushed it to npm. I'm suggesting you to link back to the package from the README, to prevent any further issues on the subject from being open.
