### ISSUE TITLE
Ensure <a> tag has a href element

### ISSUE THREAD

**Issue by kyranb** [instantpage/instant.page#11]
https://www.w3.org/TR/2016/REC-html51-20161101/textlevel-semantics.html#the-a-element

I'm using this on a page that has auto-generated <a> tag's without a href attribute and am getting `uncaught TypeError: Failed to construct 'URL': Invalid URL`

**Comment by dieulot** [comment]
Thanks, I’ve released v1.1.1 which addresses this.
