### ISSUE TITLE
Apache (WHM) + InstantPage extremely slow on mouseclick

### ISSUE THREAD

**Issue by seowner** [instantpage/instant.page#115]
I have just setup a new DO droplet, and on all my sites in the past, I use Instantpage with the mouseclick intensity.

On the new droplet, with the exact same settings... it causes the pages being prefetched to have extremely high TTFB when cache is disabled.

Devtools -> disable cache -> TTFB with IP: 1.5+ seconds! (150ms first hit, 1.5s afterwards, it's like it won't load the prefetch).

Removing the Instantpage code completely resolves this issue.

Any idea what could be causing this to happen? Did I miss an Apache setting?

Edit: Just tested with non-mouseclick, and it seems to work alright... but I would prefer to use the mouseclick version. Doesn't make sense to me why it would slow down my pages so much.

**Comment by dieulot** [comment]
This may be due to HTTP headers conflicting with prefetching; making the prefetched asset unused and fetching it again right after. Could you link to said site (here or via email)?
