### ISSUE TITLE
Browser extension?

### ISSUE THREAD

**Issue by yokoffing** [instantpage/instant.page#119]
Hi @dieulot! From what I can gather, the instant.page extension is [FasterWeb](https://chrome.google.com/webstore/detail/fasterweb/nmgpnfccjfjhdenioncabecepjcmdnjg) on the Chrome store?  This is not clear on `https://instant.page/` or this repo.

I also see a [changelog](https://instant.page/changelog) on the website for 5.2, but the Chrome store version is 1.1 and hasn't updated since January 2022. Can you clarify?

![fasterWeb](https://user-images.githubusercontent.com/11689349/227336314-b94e2644-29eb-457f-adb3-c0bb782dfb01.png)

While I'm here, I wanted to ask if FasterWeb will be good to go with Manifest V3 launching.

Thank you for your time!

**Comment by dieulot** [comment]
FasterWeb is indeed “instant.page as a Chrome plugin”.

Alas it’s not a priority for me, so I’m closing this, it’ll likely stay in its half-baked state for a while longer.

**Current state:** It incorporates an old version of instant.page, 1.x, slightly modified. It has never been updated. The January 2022 update and version bump (unrelated to the version of instant.page) was about changing the name, as the previous name “FasterChrome” was deemed to be trademark infringement.

**Manifest v3:** I plan to bring it to Manifest v3 when it becomes mandatory. Fortunately that has been indefinitely postponed, for now.

**Clearness of association to instant.page:** The nav menu on instant.page’s site links to it with the text "Chrome extension", the plugin store page shows the author as “instant.page” with a verified badge. (And the bottom of the description — that not many people will read — says it’s based on instant.page.)
The design goal of FasterWeb was to make a plugin useful to non-developers, who don’t know or care what instant.page is, so I don’t see making the association clearer as worthwhile, unless if FasterWeb were to gain options useful to web developers.

**Comment by yokoffing** [comment]
Thanks for responding! I just stumbled upon your project today. I'd love to see an update for the extension when you are able to dedicate the time.
