### ISSUE TITLE
Doesn’t work with Rocket Loader 

### ISSUE THREAD

**Issue by alesme** [instantpage/instant.page#14]
When I have a Rocket Loader (Cloudflare) on the domain, the script doesn’t work.

![image](https://user-images.githubusercontent.com/14139620/52636869-0a275000-2ece-11e9-97ca-1fa848505606.png)

**Comment by ibrokemycomputer** [comment]
I've seen  a lot of strange issues with Cloudflare + caching. I haven't heard of Rocket Loader but would love to look into this. From what I can see Rocket Loader supposedly is added to your domain/hosting - any chance you can provide the URL or confirm this isnt an issue after Cloudflare's heavy cache has updated?

**Comment by pmjcreations** [comment]
I have seen the same issue, and I have disabled Rocket Loader.

When we enable Rocket Loader, Cloudflare will insert the JS file on the fly no matter what caching setup we have within the Cloudflare

**Comment by alesme** [comment]
Yes, that's why I put this JavaScript into my custom.js, but not everyone has this option.

**Comment by dieulot** [comment]
Could someone point me to a site with Rocket Loader and instant.page? I set up [a basic website with Rocket Loader](http://kaios.fr/1.html), and it works.

**Comment by dieulot** [comment]
Closing this issue as I can’t reproduce it. If someone points me to a site where a bug happens with Rocket Loader + instant.page I’ll reopen it.
