### ISSUE TITLE
Custom header

### ISSUE THREAD

**Issue by fridzema** [instantpage/instant.page#16]
Hello, 

Is it possible to attach extra headers to the request? 
I have written my own sort of analytics where al these hover will be seen as a page visit now.

**Comment by thany** [comment]
You probably need to check a couple of [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ#As_a_server_admin.2C_can_I_distinguish_prefetch_requests_from_normal_requests.3F).

**Comment by dieulot** [comment]
What @thany said. Though it seems Chrome send `Purpose` now and not `X-Purpose` anymore.

I cannot attach a specific header alas.

Note that these pages with this header might end up being visited if the user clicks on them.

**Comment by thany** [comment]
Just a heads up: one should probably still support X-Purpose for the time being. Other Blink-based browsers may be outdated, such as Android Webview, Safari, Samsung Internet, Opera, and likely more.

**Comment by fridzema** [comment]
Thanks! For now i check on all those headers!
