### ISSUE TITLE
Missing 'crossorigin' attribute in markup

### ISSUE THREAD

**Issue by PartTimeLegend** [instantpage/instant.page#17]
Subresource integrity requires resources to enable CORS using the 'crossorigin' property. This resource doesn't. 

By adding the tag `crossorigin="anonymous"` to the included code this can be resolved.

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

**Comment by dieulot** [comment]
It’s not required; SRI works correctly without it. As far as I know it just give better errors in the console.
