### ISSUE TITLE
Make it possible to enable for specific links

### ISSUE THREAD

**Issue by david-a-wheeler** [instantpage/instant.page#2]
On a site I manage many of the links have "?" - and some should be preloaded, while others must not.  Adding `data-instant-allow-query-string` is difficult; then I have to look at every link that *might* be on the page in any possible circumstance.

It'd be far better to have a simple way to say "please enable instant.page for THIS link". E.g., support a new class "preload-on-hover" on "a".  If that class is present, then preload on hover.  Then I can add it to just the important links that I know are safe, and slowly add them over time.

Thanks!

**Comment by leesalminen** [comment]
I second this! I'm going to give it a go and submit a PR next week. 

In my use case, I only want to enable preloading for `<a>` tags within the main navigation bar. Would be easier to have an "opt in" vs an "opt out".

**Comment by adamschwartz** [comment]
You can pretty easily implement this yourself by adding the `data-no-instant` attribute programmatically, e.g.:

```html
<body>
  <a href="/path" data-instant>Link text</a>

  <!-- ... -->

  <script>
    document.querySelector('a:not([data-instant])').forEach((link) => {
      link.setAttribute('data-no-instant', '')
    })
  </script>
  <script src="//instant.page/1.0.0" type="module" integrity="sha384-6w2SekMzCkuMQ9sEbq0cLviD/yR2HfA/+ekmKiBnFlsoSvb/VmQFSi/umVShadQI"></script>
</body>
})
```

@leesalminen in your case you could even set the selector to `'nav a'` (e.g.) if you didn’t want to manually add the `data-instant` attribute to your navigation links.

**Comment by dieulot** [comment]
I reckon this would be easier. I’m going to add it.

**Comment by dieulot** [comment]
Version 1.1.0 is now shipped which addresses this.

**Comment by david-a-wheeler** [comment]
Awesome! Thanks for data-instant!
