### ISSUE TITLE
Debouncing

### ISSUE THREAD

**Issue by thany** [instantpage/instant.page#20]
Sweeping the mouse cursor across the page may potentially prefetch loads and loads of links, clogging up the server load. I think it will be beneficial if hovering links was debounced. So we first need to know how much time it takes, on average, for a user to hover into a link, and out again. Then debounce it at that sort of rate.

I get the feeling that hover->click takes a LOT more time than mouseover->mouseout, so debouncing hovers might not impact the just-in-time prefetching by all that much in practise.

**Comment by dieulot** [comment]
There’s already a 65 ms delay before preloading kicks in, which solves this. It’s explained in the Cheating latency section [on the home page](https://instant.page/).
