### ISSUE TITLE
t.target.closest is not a function

### ISSUE THREAD

**Issue by PikachuEXE** [instantpage/instant.page#23]
https://github.com/instantpage/instant.page/blob/v1.2.1/instantpage.js#L52

Most of them are from Chrome 59+ / Edge 17.17134
Which should support `Element.closest`

I do plan to add polyfill for `Element.closest` 
but I don't think it's related to most browsers that raises this error for us

**Comment by dieulot** [comment]
Could you link to a page where this happens? Do you know on which links this happens?

**Comment by PikachuEXE** [comment]
I can't reproduce it locally
And I cannot enable it on production until there is [whitelist mode](https://github.com/instantpage/instant.page/issues/18 is added)

Maybe whitelisting only certain links (common navbar/footer, frequently used link buttons...)
would solve this issue for us as well

No way to tell what's causing it for now
Let me reopen this issue once I got similar error reports again

**Comment by dieulot** [comment]
This is fixed (with a check on `event.target.closest`) in v5.1.1. https://github.com/instantpage/instant.page/commit/00249af912beabe77ecd902ebcef190d698adc81
