### ISSUE TITLE
W3C Validation. Integrity or Module

### ISSUE THREAD

**Issue by thisisfed** [instantpage/instant.page#28]
If I try to validate my page on W3c it says: "A script element with an integrity attribute must not have a type attribute with the value module."

**Comment by dieulot** [comment]
It’s a bug in the HTML spec.
Explanation: https://github.com/whatwg/html/issues/2382#issuecomment-462774170
Issue: https://github.com/whatwg/html/issues/4358

**Comment by dieulot** [comment]
I just fixed it. https://github.com/whatwg/html/pull/4843 Give it a bit of time and validators should update.
