### ISSUE TITLE
Update Readme with more details

### ISSUE THREAD

**Issue by co16353sidak** [instantpage/instant.page#30]
I am new here and I am in love with how amazing this is.
I noticed that even though the website is very informative in describing what this repo achieves, the readme is not able to do so,
I would love to modify the readme to make it such that a contributor like me who reaches to this repo will be able to understand it's working without having to open the website.

It is a minor issue which I would love to work on as my first issue here.

**Comment by dieulot** [comment]
The readme redirects to the website on purpose so that readers can experience the effect when reading, with the “Test your clicking speed” and the instant navigation, sorry.
