### ISSUE TITLE
Pages being loaded a second time after click

### ISSUE THREAD

**Issue by blogtutor** [instantpage/instant.page#4]
When I hover over a link, I can see it preloading the next page.  However, after I click, the browser is loading the page again. Tested this in Chrome 71 and Firefox 65 with the same result.

Here's the network tab in Chrome, with "Preserve Log" enabled.  The first row is from when I hovered (I was on one of the other pages of the site, and was headed back to the home page). The second row is what happened after I clicked.

![image](https://user-images.githubusercontent.com/24479276/52537592-449dbb00-2d1d-11e9-9efd-6f13a908700f.png)

So it seems that the page is preloading okay, but then the browser isn't actually utilizing it -- instead it's just loading again from scratch. ?

**Comment by holdit** [comment]
Can it be because you have "disable cache" enabled on dev tools?

**Comment by blogtutor** [comment]
Oh good grief! You're absolutely right!  🤦‍♂️ 

Thanks!
