### ISSUE TITLE
Add a setting for the mouseover timer

### ISSUE THREAD

**Issue by Calinou** [instantpage/instant.page#40]
I noticed [the mouseover timer is currently hardcoded to 65 ms](https://github.com/instantpage/instant.page/blob/9faa994f88197acc81d9e8acc952bbf185b530b8/instantpage.js#L66). Would it be possible to add a setting to change it?

I'd like to lower it on a static website to squeeze the most possible performance, considering HTTP requests are cheap in comparison to a dynamic website :slightly_smiling_face:

**Comment by dieulot** [comment]
Shipped in 2.0! https://instant.page/intensity#custom-delay
