### ISSUE TITLE
Add defer attribute to default snippet so it loads last

### ISSUE THREAD

**Issue by coliff** [instantpage/instant.page#42]
I noticed that 'instant.page' was loading on https://instant.page/ with High Priority, which meant that it was loading before other scripts on the page. I added instant.page to my own site and saw it was loading with 'Medium Priority' (even though it was at the very bottom of the page) which meant that it was loading before some images on the page. I think it'd be good if instant.page always loaded last.

I added 'defer' attribute to the snippet on my site so it always loads last and was thinking you could recommend the same?

**Comment by dieulot** [comment]
It’s done, thanks for the suggestion.

**Comment by coliff** [comment]
cool :-)  can you add `defer` to the WordPress plugin too? Right now it is:
`<script type="module" src="/wp-content/plugins/instant-page/instantpage.js"></script>`
but I'd prefer:
`<script type="module" src="/wp-content/plugins/instant-page/instantpage.js" defer></script>`
especially since that script is in the head rather than at the bottom of the body.

**Comment by dieulot** [comment]
I’ll do it when instant.page has a new version!
