### ISSUE TITLE
Supported browser

### ISSUE THREAD

**Issue by szepeviktor** [instantpage/instant.page#48]
Pleaae consider including this link in the docs
https://caniuse.com/#feat=es6-module
Thanks!

**Comment by cxq** [comment]
Well, I'd rather prefer not having module as it is not really including ES6 features.
Also "closest" method isn't supported on IE and edge 12-14

**Comment by dieulot** [comment]
The “Technical details” page says which browsers are compatible and I think it’s clearer that way. This link tells less than half the story because you also have to consider which browsers support prefetch and their quirks (for Firefox re-downloading if it’s not in cache).

**Comment by szepeviktor** [comment]
https://instant.page/tech

Thank you.
Although I miss exact version numbers.
