### ISSUE TITLE
Minify...

### ISSUE THREAD

**Issue by MattWilcox** [instantpage/instant.page#49]
This is an awesome project, but every one I've used it on and then had a co-worker run PageSpeed Insights had deducted points and thrown warnings about this not being minified...

Any chance of hosting / providing a minified version?

**Comment by dieulot** [comment]
Hi, currently it’s not minified because it fits in a single TCP packet (≤1.4kB) so there would be no advantage. When I add more features and the compressed script size exceeds 1.4kB I will minify.

**Comment by kkmuffme** [comment]
+1

**Comment by dieulot** [comment]
Do you have a PageSpeed Insights URL where points are deducted because it’s not minified? I’ve never witnessed that myself.

**Comment by dieulot** [comment]
instant.page v2.0.1 has been released and it’s now minified.

**Comment by MattWilcox** [comment]
Sorry, only just seen this - nope, no examples as I've had to manually save, minify, and self-host the file every time it got flagged. Nice to see it now minified by default, thanks :)

**Comment by kkmuffme** [comment]
@dieulot just downloaded https://github.com/instantpage/instant.page/archive/v2.0.1.zip but there's no minified .js inside?

**Comment by dieulot** [comment]
From the repo you need to minify it yourself (see the readme). Otherwise grab the minified script at https//instant.page/2.0.1
