### ISSUE TITLE
Link to external pages

### ISSUE THREAD

**Issue by batbyR** [instantpage/instant.page#5]
Hi!

Thanks for your project! ⚡

I am currently using it to quickly render my bookmarks. 

But I faced some issue: why do you forbid the redirection to external websites?

```
 if (urlObject.origin != location.origin) {
    return
  }
```

Do you think it would be worth adding a website whitelist here? I can submit a PR.

Congratulations for this repo!

**Comment by jerodev** [comment]
I suppose this is because the project is meant to speed up your own website and not external websites.
However, I do see why this might be useful in some cases.

**Comment by batbyR** [comment]
Hi @jerodev,

I see your point.

Can we imagine manually whitelist some external links as we do for query strings ?

![image](https://user-images.githubusercontent.com/13064661/52556496-07086300-2ded-11e9-9ed9-828bd080f934.png)

**Comment by aghorler** [comment]
This would be especially useful for websites broken down into sub-domains (eg. links to `signup.example.com` instead of `example.com/signup`).

**Comment by scitronboy** [comment]
Also websites might lose visitors when an external website takes too long to load.

**Comment by dieulot** [comment]
I’m open to it. [quicklink](https://github.com/GoogleChromeLabs/quicklink)’s readme states that cross-origin requests might bring [CORB](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md) and [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issues but in my experience they just work. This might be about quicklink’s fallback to Ajax.

I’ve asked quicklink’s Addy Osmani about it [on Twitter](https://twitter.com/Dieulot/status/1097822285384372225). If I hear back positively (or don’t hear back) support for external links will be implemented, probably enabled with an attribute such as `data-instant-allow-external-links` on the <body>.

**Comment by batbyR** [comment]
Great @dieulot ! 👍 

I have updated my pull request according to your implementation.

**Comment by dieulot** [comment]
Okay, this is in. v1.2.0 will let you allow external links with an `data-instant-allow-external-links` attribute on the &lt;body&gt; or with a `data-instant` attribute on the link.
