### ISSUE TITLE
Data Instant Intensity

### ISSUE THREAD

**Issue by BayuAngora** [instantpage/instant.page#51]
I read this on your website but seems unclear ->

>  Then add data-instant-intensity="mousedown" as an attribute to the <body>.

How to add that exactly? 

> <script src="//instant.page/2.0.0" type="module" defer integrity="sha384-D7B5eODAUd397+f4zNFAVlnDNDtO1ppV8rPnfygILQXhqu3cUndgHvlcJR2Bhig8"></script>
> <script data-instant-intensity="mousedown"></script>

Like that? 

Also, is there a way to make everything instant when page start display? Not when hover or mousedown?

**Comment by dieulot** [comment]
Like this: `<body data-instant-intensity="mousedown">`

The next version will have an option to preload everything as soon as the links are displayed on the page. If you want that behavior right now it’s available with [the quicklink library](https://github.com/GoogleChromeLabs/quicklink).
