### ISSUE TITLE
instant.page works only on main page (self hosted)

### ISSUE THREAD

**Issue by Eckybrazzz** [instantpage/instant.page#55]
Hi,

I have instant.page self hosted, the latest version 2.0.0.1 on a WordPress site. It only works on the main page, on other pages I get a 404.

Placed the code exactly before the /body> in the footer.

Main page:
![image](https://user-images.githubusercontent.com/30936842/66726702-4fab6c80-ee11-11e9-8f75-0562e84fdd82.png)

Sub page:
![image](https://user-images.githubusercontent.com/30936842/66726657-18d55680-ee11-11e9-8ecd-09455849e486.png)

**Comment by dieulot** [comment]
Could you share the URL of your site?

**Comment by Eckybrazzz** [comment]
Just sent a email. Rather not sharing URL's on GitHub

**Comment by Eckybrazzz** [comment]
Removed self hosting, installed WordPress Plugin. Now it OK. Rather strange, did only load on main page, now all pages. To bad, like to self host everything.

**Comment by dieulot** [comment]
The instant.page version in WordPress plugin is self-hosted!

**Comment by Eckybrazzz** [comment]
Hint: Change/add test on website that it is self hosted for WordPress users!

**Comment by Eckybrazzz** [comment]
Hint: Change/add test on website that it is self hosted for WordPress users!
