### ISSUE TITLE
t.target.closest is not a function

### ISSUE THREAD

**Issue by kkmuffme** [instantpage/instant.page#58]
As opened (but closed) here already https://github.com/instantpage/instant.page/issues/23 I also get this issue.

In 2.0.1 (using the .min version, it's o.target.closest) and also in 3.0.0

I am not exactly sure why/how, but I can provide a user agent that encountered this error:
Mozilla/5.0 (iPhone, CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

The issue happened on a page which contained a facebook fbclid, but I don't think that is causing the issue (but who knows)

Is this info any useful for debugging/fixing this?

**Comment by dieulot** [comment]
Could you link to the page where that is happening?

**Comment by kkmuffme** [comment]
I have one, but I cannot reproduce it there (same user agent)

**Comment by dmalis** [comment]
Seeing these all the time; iOS, FBapp -> webview

**Comment by kkmuffme** [comment]
@dmalis great find

**Comment by dieulot** [comment]
Closing this as it’s a dupe or #23. If you have any more info please direct them there.

**Comment by dieulot** [comment]
This is fixed (with a check on `event.target.closest`) in v5.1.1. https://github.com/instantpage/instant.page/commit/00249af912beabe77ecd902ebcef190d698adc81
