### ISSUE TITLE
Ignore links with onclick events

### ISSUE THREAD

**Issue by lukencode** [instantpage/instant.page#6]
Just a suggestion - I've been trying this out with a couple of legacy sites that do some dodgy stuff with onclick attributes. It is stuff like GET requests deleting resource but not until a confirm prompt.. Would checking for the onclick attribute and ignoring those links be useful?

**Comment by dieulot** [comment]
Click events might be used for something as simple as tracking clicks, so I don’t want to automatically disable those. I recommend using `data-no-instant` attributes on problematic links.
