### ISSUE TITLE
Safari support for v3?

### ISSUE THREAD

**Issue by verlok** [instantpage/instant.page#62]
On https://instant.page/tech I see 

> Incompatible browsers
> Safari 13.0 has support for `<link rel="prefetch">` but it’s disabled by default. Hopefully it will be enabled in March.

Is that still true?

**Comment by verlok** [comment]
And with "March" you intend March of which year?

**Comment by verlok** [comment]
I can see from here it's true https://caniuse.com/#feat=link-rel-prefetch
So you mean that instant page doesn't have any effect on Safari?

**Comment by dieulot** [comment]
March of this year. Though it’s February and Apple has yet to enable it by default. Maybe for September then…

In the mean time I plan to make a reboot of [InstantClick](http://InstantClick.io/) renamed “instant.page extra” that will work in Safari starting from 12.1.

**Comment by verlok** [comment]
I’m getting confused with all of those names and versions. Now I’m thinking to use QuickLink but only on the mobile version of the websites. 

I liked the idea behind InstantPage v3. Why don’t you make only one script (meaning name it in a single way) that works everywhere?

**Comment by dieulot** [comment]
instant.page’s way of preloading doesn’t work in Safari. InstantClick’s way of preloading works nearly everywhere but it transforms a site into an SPA, so it needs additional work to function correctly. quicklink’s way of preloading in Safari doesn’t work if you don’t have cache headers, most pages don’t have those so I don’t include a fallback like they do.

**Comment by verlok** [comment]
We have cache headers and the vast majority of our user base is on Safari, so using QuickLink on mobile is probably a good idea. Thanks

**Comment by dieulot** [comment]
Given that Safari still doesn’t ship prefetch by default, I plan to reevaluate the fallback options for it.
