### ISSUE TITLE
New releases need descriptions

### ISSUE THREAD

**Issue by optimocha** [instantpage/instant.page#68]
Not exactly an issue, so feel free to close it when you see this message, bu here's something interesting about GitHub:

https://github.community/t5/How-to-use-Git-and-GitHub/Not-getting-release-notification-despite-quot-Watching-releases/m-p/19665/highlight/true#M5866

Just stumbled upon your new release by chance, didn't get an email although I'm "watching" your releases. Turns out new releases without messages don't send notifications to your watchers.

Cheers!

**Comment by optimocha** [comment]
PS: I'm not 100% sure but I think it's possible to edit releases to add messages/descriptions.

**Comment by dieulot** [comment]
Closing as I don’t do, and don’t plan to do, GitHub releases and [it seems](https://github.com/instantpage/instant.page/releases) they’re not automatically made from tags.
