### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource - in the console of a Django siet

### ISSUE THREAD

**Issue by reyesvicente** [instantpage/instant.page#79]
I placed your script inside my javascript block in the `base.html`below the other javascript scripts but I'm getting this:

```Failed to find a valid digest in the 'integrity' attribute for resource 'https://instant.page/5.1.0' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.```

**Comment by max-bruhn** [comment]
same for me. i integrated the exact code from the page into a shopfiy theme and i get the same error
