### ISSUE TITLE
Not compatible with SPA navigation

### ISSUE THREAD

**Issue by alicescfernandes** [instantpage/instant.page#80]
Can we have a version that doesn't uses const? I'm currently mantaining an app that persists the state (the window variable) and one thing: either the scripts is loaded at every navigation, causing it to break due to to reatributting const variables

**Comment by dieulot** [comment]
The script is designed to be loaded as a module script (`type=module` in HTML or `import()` in JS) and not as a classic script, doing so will avoid variables trying and failing to be reassigned.
