### ISSUE TITLE
Instant Page minified polluting scope

### ISSUE THREAD

**Issue by alicescfernandes** [instantpage/instant.page#81]
We should have. a IIFE wrapped around this module to avoid reassigment of variables. If i use the non minified version, this doesn't happen, but when i use the minified version, i get this error:

![image](https://user-images.githubusercontent.com/15971182/89182830-3fc26c00-d58e-11ea-8216-06b7f1c10734.png)

With an IIFE this should be solved.

**Comment by digitaljhelms** [comment]
https://github.com/instantpage/instant.page/pull/83

**Comment by alicescfernandes** [comment]
Thanks :+1:
