### ISSUE TITLE
Optimize memory if !isSupported

### ISSUE THREAD

**Issue by crazy4groovy** [instantpage/instant.page#9]
Hi, cool lib! I think you can save a bit of js memory around `if (isSupported) {`
https://github.com/instantpage/instant.page/blob/master/instantpage.js#L11

You don't need to define any functions at all in this case, since they are never referenced. Maybe just an early exit from the module would be better? eg. `if (!isSupported) return`

**Comment by dieulot** [comment]
`return` isn’t supported outside of functions, the solution would be to wrap every function in an `if`, but that would make the code ugly so I won’t do it.

**Comment by kurtextrem** [comment]
Another solution would be using `const xy = function xy() {}` to define functions instead of `function xy{}`, which prevents hoisting of functions.
