### ISSUE TITLE
Drupal 7 version

### ISSUE THREAD

**Issue by bcollin** [instantpage/instant.page#93]
Not really an issue but I did not know how else to contact you: 

I made a Drupal 7 module that implements Instant.Page in a similar fashion as your Wordpress plugin. You can find it at https://github.com/bcollin/instantpage-d7 .

Question: I can see how this would be useful on fast websites. Going from 500 ms to 300 ms is a real gain. Does Instant.page have advantages for slow websites?

**Comment by dieulot** [comment]
Thanks, sorry for the late reply. Yes, preloading is still useful on very slow sites, although it is much less noticeable.
