### ISSUE TITLE
Not working for Wordpress i installed the plugin

### ISSUE THREAD

**Issue by khanakia** [instantpage/instant.page#95]
Hi,

I installed the plugin on my website https://www.khanakia.com/ and when i hover on link i can see it tries to send request to load the page. But when i click the link it takes the same amount of time. No change at all. You can check the link i provided

**Comment by niccoX** [comment]
Can you show me how you checked that it sends request. I tried with Inspect elements Network tab, but the file is not loading there.

**Comment by khanakia** [comment]
@niccoX I am not using this plugin anymore. No support and community at all. I uninstalled it.
I added this request 4 months ago LOL
